Home task 10
isken24/python_for_dqe pull request #10
Opened 2022-11-14 06:23 UTC by isken24

Home task 10 is ready for review. Minor refactoring in home_task_04_part_2, home_task_06, home_task_09.

2022-11-15 05:47 UTC, dena-den requested changes

2022-11-15 05:47 UTC, dena-den commented on hw_10/home_task_10.py
> +                self.c.execute("""CREATE TABLE news (
You can use syntax `CREATE TABLE if not exists`
It's prevent error with already existed table.

2022-11-15 05:47 UTC, dena-den commented on hw_10/home_task_10.py
> +
Excess newline.

2022-11-15 05:47 UTC, dena-den commented on hw_10/home_task_10.py
> +
Excess newline.

2022-11-15 05:47 UTC, dena-den commented on hw_10/home_task_10.py
> +                self.c.execute("""CREATE TABLE news (
Please, create column `id` for each table. It's good practice.

2022-11-15 05:47 UTC, dena-den commented on hw_10/home_task_10.py
> +                self.c.execute("""CREATE TABLE news (
And where is duplicate check? In try-except construction? Make it clearer.

2022-11-15 18:29 UTC, isken24 commented on hw_10/home_task_10.py
> +
Deleted excessive newline

2022-11-15 18:29 UTC, isken24 commented on hw_10/home_task_10.py
> +
Deleted excessive newline

2022-11-15 18:34 UTC, isken24 commented on hw_10/home_task_10.py
> +                self.c.execute("""CREATE TABLE news (
Thank you for the tip with existing table check! Fixed that, added `id` column.
No-duplicate check is at the end of `self.c.execute("""CREATE TABLE` statement. I'm checking only "all columns" duplicates, since same news may appear in different cities and on different dates, for the Advertisements I'm applying the same logic.

2022-11-16 16:33 UTC, dena-den approved these changes
Excellent!

2022-11-16 16:33 UTC, dena-den commented on feed_writer.py
>      JSON = '.json'
For which purpose do you use variables here?
It seems that they don't optimize your code, don't make it more compact and so on. But they make it a little bit harder to read.
Just you hardcode for .endswith() func instead of them.

2022-11-16 16:33 UTC, dena-den commented on hw_06/home_task_06.py
> +        return self.number_of_days_left
Do you need a return here?

2022-11-16 16:33 UTC, dena-den commented on hw_06/home_task_06.py
> +        return self.number_of_days_left
It's cool that you reworked it!

2022-11-16 16:33 UTC, dena-den commented on hw_06/home_task_06.py
> +    #os.remove(input_file.path)
Forgot.

2022-11-16 16:33 UTC, dena-den commented on hw_08/home_task_08.py
> +            #os.remove(self.filepath)
And here:)

2022-11-16 16:33 UTC, dena-den commented on hw_10/home_task_10.py
> +                           UNIQUE (news_text, city, publication_date)
Why do you need UNIQUE() here? It's like a composite key?
Just explain me, I don't get it

2022-11-16 16:33 UTC, dena-den commented on hw_10/home_task_10.py
> +        #os.remove(input_xml)
Here

2022-11-16 16:37 UTC, dena-den commented on hw_10/home_task_10.py
> +                           UNIQUE (news_text, city, publication_date)
Seems I got it - for duplicates check?

2022-11-16 16:48 UTC, isken24 commented on hw_10/home_task_10.py
> +        #os.remove(input_xml)
oooops(2)

2022-11-16 16:48 UTC, isken24 commented on hw_10/home_task_10.py
> +                           UNIQUE (news_text, city, publication_date)
yes, you are right

2022-11-16 16:48 UTC, isken24 commented on hw_08/home_task_08.py
> +            #os.remove(self.filepath)
oooops(1)

2022-11-16 16:48 UTC, isken24 commented on hw_06/home_task_06.py
> +        return self.number_of_days_left
Looks like it is redundant, deleted it

2022-11-16 16:48 UTC, merged