Home task 03
isken24/python_for_dqe pull request #3
Opened 2022-10-03 07:14 UTC by isken24

Home task 03 is ready for review.

2022-10-03 09:35 UTC, dena-den requested changes
Correct and short solution, but it's a bit hard to understand.

2022-10-03 09:35 UTC, dena-den commented on home_task_03.py
> +abstract = abstract.replace('\n\n', '\n')
Maybe better to use: abstract = abstract.replace().replace()? In one row.

2022-10-03 09:35 UTC, dena-den commented on home_task_03.py
> +# We will iterate through each line of the text and then divide each line into independent sentences.
"""Use block comments
for commenting several rows.
"""

2022-10-03 09:35 UTC, dena-den commented on home_task_03.py
> +    result = result.replace('.  ', '. ').strip()
Why do you use double spaces? Don't quite understand.

2022-10-03 09:35 UTC, dena-den commented on home_task_03.py
> +    result += '\n'
Maybe better to use result as list variable (not string). And just 'join' it using '\n' at the end?

2022-10-03 09:35 UTC, dena-den commented on home_task_03.py
> +    for i in result:
'i'? Ex. 'one_symbol'

2022-10-03 09:35 UTC, dena-den commented on home_task_03.py
> +        if i.isspace():
re.findall('\s', abstract) - looks shorter and clearer. And matches all Unicode whitespace characters (which includes [ \t\n\r\f\v]).

2022-10-03 09:35 UTC, dena-den commented on home_task_03.py
> +    print(f"Number of Spaces : {str(space_counter)}.")
str() here is redundantly.

2022-10-05 03:53 UTC, isken24 commented on home_task_03.py
> +abstract = abstract.replace('\n\n', '\n')
Thanks for the advice, didn't think about it that way. Corrected solution.

2022-10-05 03:53 UTC, isken24 commented on home_task_03.py
> +# We will iterate through each line of the text and then divide each line into independent sentences.
Implemented block comments.

2022-10-05 03:53 UTC, isken24 commented on home_task_03.py
> +    result = result.replace('.  ', '. ').strip()
I used double spaces to implement indent in the beginning of each line.

2022-10-05 03:54 UTC, isken24 commented on home_task_03.py
> +    result += '\n'
In this case it will return each sentence on separate line and resulting abstract will have different structure from original abstract.

2022-10-05 03:55 UTC, isken24 commented on home_task_03.py
> +    for i in result:
Deleted that part of the code.

2022-10-05 03:56 UTC, isken24 commented on home_task_03.py
> +        if i.isspace():
Thank you for the advice, changed code according to this comment.

2022-10-05 03:56 UTC, isken24 commented on home_task_03.py
> +    print(f"Number of Spaces : {str(space_counter)}.")
Deleted that part of the code.

2022-10-05 08:36 UTC, dena-den requested changes
Nice solution! 
Make these changes and I will approve it.

2022-10-05 08:36 UTC, dena-den commented on home_task_03.py
> +ABSTRACT = """homEwork:
My mistake. Please use lowercase.

2022-10-05 08:36 UTC, dena-den commented on home_task_03.py
> +            space_counter += len(re.findall(r'[\s]', statement))
You can use re.findall() for the whole text without iteration.

2022-10-05 08:47 UTC, dena-den commented on home_task_03.py
> +def count_number_of_spaces(result):
Please, add attribute typing.

2022-10-05 10:43 UTC, isken24 commented on home_task_03.py
> +ABSTRACT = """homEwork:
Renamed to lowercase

2022-10-05 10:43 UTC, isken24 commented on home_task_03.py
> +            space_counter += len(re.findall(r'[\s]', statement))
Changed code in order to use re.findall() for the whole text without iteration

2022-10-05 10:44 UTC, isken24 commented on home_task_03.py
> +def count_number_of_spaces(result):
Added typing here

2022-10-05 10:50 UTC, dena-den requested changes

2022-10-05 10:50 UTC, dena-den commented on home_task_03.py
> +for row in result:
Why don't you use join() func?
And it's bad practice to use data types in naming (`string`). I think, just `result` is better.

2022-10-05 10:50 UTC, dena-den commented on home_task_03.py
> +    for line in result:
Here you can just print(string_result)

2022-10-05 12:29 UTC, isken24 commented on home_task_03.py
> +for row in result:
I didn't have much experience with join(). Thanks for advice, it was nice to practice this approach.
Also renamed variable.

2022-10-05 12:30 UTC, isken24 commented on home_task_03.py
> +    for line in result:
Implemented changes here according to your comment

2022-10-05 12:35 UTC, dena-den commented
Approved!

2022-10-05 12:38 UTC, merged