Home Task 05
isken24/python_for_dqe pull request #5
Opened 2022-10-16 17:51 UTC by isken24

Home Task 05 is ready for review.

2022-10-17 10:04 UTC, dena-den requested changes

2022-10-17 10:04 UTC, dena-den commented on home_task_05.py
> +    record = News()
record = News(text_of_news, city)

2022-10-17 18:56 UTC, isken24 commented on home_task_05.py
> +        result.write(f'{record.header}'
Fixed according to request.

2022-10-17 18:56 UTC, isken24 commented on home_task_05.py
> +    header = 'News -------------------------\n'
Deleted those variables.

2022-10-17 18:56 UTC, isken24 commented on home_task_05.py
> +    def add_timestamp(self):
Got rid of this method.

2022-10-17 18:57 UTC, isken24 commented on home_task_05.py
> +                print('Good buy!')
Looks like I'm willing to sell my program :D

2022-10-17 18:57 UTC, isken24 commented on home_task_05.py
> +                continue
Thanks for advise!

2022-10-17 19:02 UTC, isken24 commented on home_task_05.py
> +                print(f'Input value must be single digit from 0 to 3!')
Didn't manage to do it other way and make it work as it supposed to.

2022-10-17 19:02 UTC, isken24 commented on home_task_05.py
> +    record = News()
Fixed according to request.

2022-10-18 11:20 UTC, dena-den requested changes
Nice. Few improvements in naming.
And another one thought, could you create parent class for all types of publication? And implement in this class common parameters (if you can find so) or at least create method to write publication to file. 
Because there we have 3 types of publications and they should be connected together (using parent class).

2022-10-18 11:20 UTC, dena-den commented on home_task_05.py
> +        self.publication_date = datetime.now().strftime("%Y/%m/%d %H:%M")
Why don't you use underscores here, like __publication_date?

2022-10-18 11:20 UTC, dena-den commented on home_task_05.py
> +            print('Choose type of record: 1 - News, 2 - Private Ad, 3 - Random Fact, 0 - EXIT PROGRAM')
3 - isn't a fact

2022-10-18 11:20 UTC, dena-den commented on home_task_05.py
> +    def number_of_days_left(self):
better `get_number_of_days_left`

2022-10-19 17:33 UTC, isken24 commented on home_task_05.py
> +            print('Choose type of record: 1 - News, 2 - Private Ad, 3 - Random Fact, 0 - EXIT PROGRAM')
Fixed

2022-10-20 13:28 UTC, dena-den commented on home_task_05.py
> +        self.publication_date = datetime.now().strftime("%Y/%m/%d %H:%M")
Good decision, especially if it's more Pythonic.

2022-10-21 06:54 UTC, merged