Home task 07
isken24/python_for_dqe pull request #7
Opened 2022-11-02 15:15 UTC by isken24

Home task 07 is ready for review.

2022-11-04 17:25 UTC, dena-den requested changes
Let's have a call!

2022-11-04 17:25 UTC, dena-den commented on hw_07/home_task_07.py
> +        self.words_count = {}
I suggest to move creation of empty dicts inside of the functions.

2022-11-04 17:25 UTC, dena-den commented on hw_07/home_task_07.py
> +                letter_percentage = round(self.letters_count[key] / self.total_number_of_letters * 100, 3)
1. I think, that you forget to count uppercase letters for letter_percentage.  You count only self.letters_count[key], but there is self.upper_letters_count too.
2. Again, maybe it's possible to union these two iterators in one? Less iterations - faster. But maybe in such case logic will be too complicated.

2022-11-04 17:25 UTC, dena-den commented on hw_07/home_task_07.py
> +
Excess empty string.

2022-11-04 17:25 UTC, dena-den commented on hw_07/home_task_07.py
> +    content = source_file.content.replace('_', '').replace('\n\n', '')
Why didn't you replace characters inside of  __init__ method in Counter class?

2022-11-04 17:25 UTC, dena-den commented on hw_07/home_task_07.py
> +    letters_count = counter.letters_count
You create too much classes (4!). Because of that you need to do this.
My suggestion: create 1-2 classes instead of 4. And in such case it will be possible to pass arguments inside object. Without creating these unnecessary variables.

2022-11-04 17:27 UTC, dena-den commented on hw_07/home_task_07.py
> +                letter_percentage = round(self.letters_count[key] / self.total_number_of_letters * 100, 3)
Too much precision. 
In my opinion, 1-2 digit after point is enough in this case.

2022-11-07 07:06 UTC, isken24 commented on hw_07/home_task_07.py
> +""" Home Task 7:
Fixed

2022-11-07 07:07 UTC, isken24 commented on hw_07/home_task_07.py
> +        for line in self.text.lower().split('\n'):
Thanks for advice, fixed code here

2022-11-07 07:08 UTC, isken24 commented on hw_07/home_task_07.py
> +                        self.words_count[word] = 1
Changed code with use of dict.get()

2022-11-07 07:08 UTC, isken24 commented on hw_07/home_task_07.py
> +    def letters_counter(self) -> dict:
Fixed

2022-11-07 07:10 UTC, isken24 commented on hw_07/home_task_07.py
> +                            self.total_number_of_letters += 1
Implemented re.sub() here, to create single string from all words glued together

2022-11-07 07:10 UTC, isken24 commented on hw_07/home_task_07.py
> +        self.words_count = {}
Fixed

2022-11-07 07:13 UTC, isken24 commented on hw_07/home_task_07.py
> +                letter_percentage = round(self.letters_count[key] / self.total_number_of_letters * 100, 3)
self.letters_counter() processes all letter from the text, because lower() method was implemented to the whole text earlier

2022-11-07 07:13 UTC, isken24 commented on hw_07/home_task_07.py
> +
Fixed

2022-11-07 07:14 UTC, isken24 commented on hw_07/home_task_07.py
> +    content = source_file.content.replace('_', '').replace('\n\n', '')
Thanks for pointing it out! Moved replace() to init method

2022-11-07 07:15 UTC, isken24 commented on hw_07/home_task_07.py
> +    letters_count = counter.letters_count
Changed code to get rid of redundant classes

2022-11-07 07:15 UTC, isken24 commented on hw_07/home_task_07.py
> +                letter_percentage = round(self.letters_count[key] / self.total_number_of_letters * 100, 3)
Changed precision to 1 digit after comma

2022-11-07 10:49 UTC, dena-den commented on hw_07/home_task_07.py
> +                            self.total_number_of_letters += 1
Nice decision!

2022-11-08 08:10 UTC, dena-den approved these changes
Correct `return`s and it's approved!

2022-11-08 08:10 UTC, dena-den commented on hw_07/home_task_07.py
> +        return self.words_count
`return` isn't needed if you work with object attributes (self.variable).
So just delete them here and after. And accordingly change typization to `-> None`.

2022-11-08 08:46 UTC, merged