Home task 08
isken24/python_for_dqe pull request #8
Opened 2022-11-07 05:20 UTC by isken24

Home task 08 is ready for review.

2022-11-07 10:31 UTC, dena-den requested changes
You should change format of JSON-file. It must have key-value pairs for each of required parameters.
E.g. 'news_text', 'city' or 'ad_date' keys where it's needed.
Not only 'content' key where you pass everything.

2022-11-07 10:31 UTC, dena-den commented on hw_08/home_task_08.py
> +    def __init__(self, file_path=None):
You can pass alternative path as a default parameter in variable `file_path`. And if-clause will not be needed.

2022-11-07 18:57 UTC, isken24 commented on hw_08/home_task_08.py
> +from home_task_06 import create_news, create_private_ad, add_greeting
Fixed

2022-11-07 19:14 UTC, isken24 commented on hw_08/home_task_08.py
> +    def __init__(self, file_path=None):
Fixed code as you suggested, but couldn't get rid of if-clause completely, so now it is in `__main__` section :(
Alternative file path should be read from console by using input() function. If user want to use standard file path, he would press Enter, leaving input() empty. And if we try to pass empty `input()` to the `file_path` without additional logic, `file_path` would become equal `""` (empty string) and code would fall with an error.

2022-11-08 08:27 UTC, dena-den commented on hw_08/home_task_08.py
> +        return self.content
return is excess.

2022-11-08 08:27 UTC, dena-den approved these changes
Get rid of one return and it's approved. Congrats!

2022-11-08 08:47 UTC, merged